### ISSUE TITLE
Sinkhorn Algorithm

### ISSUE THREAD

**Issue by kleinzcy** [LuigiRiz/NOPS#5]
Thanks your code. 

It seems that there is something wrong in your Sinkhorn Algorithm.

```
        features = torch.nn.functional.normalize(features, dim=1, p=2)
        head = torch.nn.functional.normalize(head, dim=1, p=2)
```

In my understanding, the dim of "head" is $d\times N$. It is not right to normalize along the dim 1. The right way is to normalize the head along with dim 0. Do I understand right?

**Comment by 2814894078** [comment]
**Hello, thank you very much for your code. I successfully ran the SemanticPOSS dataset, but I encountered an issue when running SemanticKITTI:**

:~/NOPS-main$ python main_discover.py -s 0 --dataset SemanticKITTI --dataset_config /home/ly/NOPS-main/config/semkitti_dataset.yaml --num_heads=5 --overcluster_factor=3 --use_scheduler --adapting_epsilon_sk --use_uncertainty_queue --use_uncertainty_loss --uncertainty_percentile=0.5

/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:446: UserWarning: Checkpoint directory checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Training: -1it [00:00, ?it/s]
Loading weights.pt ...
Epoch 0:   0%|                                                                                                                                                                                                                                   | 0/5801 [00:00<00:02, 2734.23it/s]
Traceback (most recent call last):
  File "main_discover.py", line 138, in <module>
    main(args)
  File "main_discover.py", line 132, in main
    trainer.fit(model)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 395, in _optimizer_step
    model_ref.optimizer_step(
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1616, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 206, in step
    self.optimizer_step(closure=closure, profiler_name=profiler_name, kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 128, in optimizer_step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, lambda_closure=closure, kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, kwargs)**
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/torch/optim/sgd.py", line 113, in step
    loss = closure()
  File "/

home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 536, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/home/ly/anaconda3/envs/NCD/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 172, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/ly/NOPS-main/modules/Discoverer.py", line 437, in training_step
    loss_cluster = self.loss(
  File "/home/ly/NOPS-main/modules/Discoverer.py", line 550, in loss
    weight_new[: self.hparams.num_labeled_classes] = weight_bck[
**RuntimeError: The expanded size of the tensor (14) must match the existing size (13) at non-singleton dimension 0.  Target sizes: [14].  Tensor sizes: [13]**

**My dataset configuration and code files are set exactly as you provided, and I have entered the command according to the README file you provided. Below is the structure of my dataset:**


I don't know where the problem is. I would greatly appreciate your help.
